---
apiVersion: batch/v1
kind: Job
metadata:
  name: xpan7-labsegformer-infer-{{index}}
  namespace: yn-gpu-workload
  labels:
      k8s-user: xpan7
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 60
  template:
    spec:
      nodeSelector:
        "nvidia.com/gpu.present": "true"
      securityContext:
        runAsUser: 290361
        runAsGroup: 1944271327
        fsGroup: 1944271327
      volumes:
        - name: shm
          emptyDir:
            medium: Memory
            sizeLimit: '21474836480'
        - name: lab
          persistentVolumeClaim:
            claimName: xpan7-gpu-lab
        - name: home
          persistentVolumeClaim:
            claimName: xpan7-gpu-home
      containers:
        - name: main
          image: hpcharbor.mdanderson.edu/xpan7/dlenv:xpan7
          command: ["python", "/rsrch5/home/trans_mol_path/xpan7/pipelines/artemis/segformer-infer/main_tme_k8.py"]
          args: [
            "-d", "/rsrch5/home/trans_mol_path/xpan7/data/artemis_cd45/til/1_cws_tiling",
            "-o", "/rsrch5/home/trans_mol_path/xpan7/data/artemis_cd45/mit-b3-finetunedBRCA-Artemis-e60-lr00001-s512-20x512/mask_cws512",
            "-s", "/rsrch5/home/trans_mol_path/xpan7/data/artemis_cd45/mit-b3-finetunedBRCA-Artemis-e60-lr00001-s512-20x512/mask_ss1512",
            "-p", "*.svs", "-c", "-ps", "512", "-ins", "512", "-nC", "6", "-n", "{{index}}", "-sf", "0.0625", "-nJ", "32"
            ]
          workingDir: "/rsrch5/home/trans_mol_path/xpan7"
          env:
          - name: HOME
            value: "/rsrch5/home/trans_mol_path/xpan7"
          volumeMounts:
            - name: lab
              mountPath: "/rsrch6/home/trans_mol_path/yuan_lab"
            - name: home
              mountPath: "/rsrch5/home/trans_mol_path/xpan7"
          resources:
            requests:
              nvidia.com/gpu: "1"
            limits:
              nvidia.com/gpu: "1"
          imagePullPolicy: IfNotPresent
      restartPolicy: Never

