---
apiVersion: batch/v1
kind: Job
metadata:
  name: xpan7-artemistme-infer-{{index}}
  namespace: yn-gpu-workload
  labels:
      k8s-user: xpan7
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 60
  template:
    spec:
      nodeSelector:
        "nvidia.com/gpu.present": "true"
      securityContext:
        runAsUser: 290361
        runAsGroup: 1944271327
        fsGroup: 1944271327
      volumes:
        - name: shm
          emptyDir:
            medium: Memory
            sizeLimit: '21474836480'
        - name: lab
          persistentVolumeClaim:
            claimName: xpan7-gpu-lab
        - name: home
          persistentVolumeClaim:
            claimName: xpan7-gpu-home
      containers:
        - name: main
          image: hpcharbor.mdanderson.edu/xpan7/tmesegpro:xpan7
          command: ["python", "/rsrch5/home/trans_mol_path/xpan7/pipelines/artemis/tmesegCNN-infer/main_tme_k8CNN.py"]
          args: [
            "-d", "/rsrch6/home/trans_mol_path/yuan_lab/TIER2/artemis_lei/validation/til/1_cws_tiling",
            "-o", "/rsrch6/home/trans_mol_path/yuan_lab/TIER2/artemis_lei/validation/tmeseg_artemisTCGA_finetune20xPen_K8div12v2/mask_cws",
            "-s", "/rsrch6/home/trans_mol_path/yuan_lab/TIER2/artemis_lei/validation/tmeseg_artemisTCGA_finetune20xPen_K8div12v2/mask_ss1",
            "-p", "*.svs", "-c", "-ps", "384", '-ins', '384',"-nC", "8", "-n", "{{index}}", "-sf", "0.0625"
            ]
          workingDir: "/rsrch5/home/trans_mol_path/xpan7"
          env:
          - name: HOME
            value: "/rsrch5/home/trans_mol_path/xpan7"
          volumeMounts:
            - name: lab
              mountPath: "/rsrch6/home/trans_mol_path/yuan_lab"
            - name: home
              mountPath: "/rsrch5/home/trans_mol_path/xpan7"
          resources:
            requests:
              nvidia.com/gpu: "1"
            limits:
              nvidia.com/gpu: "1"
          imagePullPolicy: IfNotPresent
      restartPolicy: Never

